# Generated by Django 5.0.6 on 2024-07-03 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,9}$', message="Telefon raqami '999999999' formatida bo'lishi kerak. Maksimal 9 ta raqam.")]),
        ),
    ]
